Fix Github module loading in CLI
Problem:
For any required Github module, the CLI would return the following and
ignore the module:
UnhandledPromiseRejectionWarning: Unhandled promise rejection (rejection id: 3):
Error: Protocol "https:" not supported. Expected "http:"

Reason:
The getGitHub plugin queried the Github Contents API, but didn't set the
User-Agent as mandated by the API rules, so the API always returned 403,
the plugin thus failed, and the original URL got resolved by
Core.Utils.getURL.

In the CLI, Core.Utils.getURL uses the "http" node module, which only
resolves HTTP, not HTTPS. However, Github uses HSTS (automatically
redirects all HTTP requests to HTTPS requests). Therefore Github modules
couldn't be downloaded from the CLI.

Fix:
* FIX Core.Utils.getURL to require either the "http" or "https" module,
  depending on the protocol
* CHANGE getGitHub to no longer use the Github Contents API, but instead
  * no longer match "githubusercontent" URLs and let them be handled by
    getURL
  * for backwards compatibility, still match the "blob" URLs, but
    rewrite them to "githubusercontent" format
* CHANGE Core.Utils.getURL to allow "getURL" processors to also return
  changed URL, not just resolved data